### PR TITLE
Feature/orbitalcontrols camera configuration

### PR DESCRIPTION
**Pull request by spark323**
This PR adds the ability for OrbitalControls to set the camera position and direction

### CODE REVIEW

**Comment by dylanebert** [comment]
Thanks :) I made a PR on your fork with some updates (copied):

- Naming, formatting for consistency
- Removed `setPosition`, since I believe it has the same function as setting `camera.position =` directly, which OrbitControls now listens for. Let me know if I'm mistaken and there is a different intended functionality
- Update the camera-updates example to test the new method

**Comment by reconlabs-chris-park** [comment]
I merged your PR and corrected an implementation error. Thanks!

**Comment by spark323** [comment]
I merged your PR and corrected an implementation error. Thanks!

**Comment by dylanebert** [comment]
Thanks! I just pushed lots of small changes but nothing that conflicts with yours. Feel free to rebase or accept my rebase PR and I'll merge

**Review by dylanebert — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
