### PR TITLE
Limit Scene with {x,z,y}{Min,Max}, also add a test framework

### PR DESCRIPTION
**Pull request by jeyemwey**
This PR will add `jest` as a test framework. It also adds a `Scene.limit` method that removes the number of visible splats based on their position.

It currently cuts out a Cuboid with the given bounding coordinates, i.e., for the bonsai scene, you can do: `scene.limit(-2, 2, -2, 2, -2, 2)`:

image

The function is currently non-destructive, you can run the function again with a larger bounding box and the cut-out splats reappear.

Also, as always with splats, the function will only check for the positions, and edges will inevitably end up fuzzy.

### CODE REVIEW

**Comment by dylanebert** [comment]
Awesome, thank you! Jest works for me, I know @xenova has experience with it as well.

For the limit method, what do you think about the following for more future extensibility?
```
scene.limit(shape: BoundingShape)
```

Then we can define a `BoundingShape.ts` class and an inherited `Box.ts` class. Or something along those lines. There could be a helper `limitBox` method in scene if you want to keep the workflow the same.

**Comment by jeyemwey** [comment]
> For the limit method, what do you think about the following for more future extensibility?
> ```
> scene.limit(shape: BoundingShape)
> ```

I like the idea but the "is point in bounding shape" function seems to get extremely complicated quickly, especially if you implement it yourself.

> There could be a helper limitBox method in scene if you want to keep the workflow the same.

We could make use of method overloading (as you did in Vector3/add) or rename the function right now to prevent a breaking change later.

**Comment by dylanebert** [comment]
I'm thinking that the `BoundingShape` could have a generic `isInBounds(point: Vector3)` method, which would allow you to implement the same behaviour, just more extensibly.

Maybe another term besides `BoundingShape` if you'd prefer since that may imply other behaviour like an explicit shape.

**Comment by dylanebert** [comment]
Actually for now I think it's fine to just name it `limitBox` and push as is :)

**Comment by jeyemwey** [comment]
> Actually for now I think it's fine to just name it `limitBox` and push as is :)

Updated the PR with new commit [c132eb3](https://github.com/dylanebert/gsplat.js/pull/22/commits/c132eb30199c97a9c11d663a36bb0803f7f0df68) according to your proposal.

**Comment by jeyemwey** [comment]
There seem to be some issues with typecasting in the test, probably becasue of an upstream change? Could @dylanebert maybe take a look into that? Just push into this branch if you want to.

**Comment by dylanebert** [comment]
I checked it out and got it working with recent changes :) (at least `limitBox`)

Since `Scene` has changed a ton, I had to remove the test for now, but kept the actions

**Review by dylanebert — APPROVED** [review]
Will merge for now, feel free to open a new PR for the specific test implementation

**Pull request merged**
