### PR TITLE
added WSAD controls

### PR DESCRIPTION
**Pull request by ruslanjabari**
very basic camera relative WASD controls

### CODE REVIEW

**Comment by dylanebert** [comment]
I think it'd be better to keep it more simple / consistent with things like [Babylon JS](https://github.com/BabylonJS/Babylon.js) Orbit Controls. Maybe there's a way it could be made more for users to extend with keyboard controls?

**Comment by ruslanjabari** [comment]
I thought BabylonJS had similar camera controls but with the arrow keys instead of WASD. Agree that it's probably better for users to extend (keyboard) controls, maybe this serves better as an example/option that users pick vs being there by default?

**Comment by dylanebert** [comment]
Oh you're right, babylon.js has default orbit keyboard controls on `ArcRotateCamera`. 

three.js [OrbitControls](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/OrbitControls.js] seems to have default keyboard panning, and modifier keyboard keys for orbit.

In that case default keyboard controls makes sense, maybe can just minimally add an optional argument to turn it off? If you can add that and rebase then works for me :)

**Comment by ruslanjabari** [comment]
done

**Comment by dylanebert** [comment]
Awesome!

I noticed a bug where if you hold a modifier like shift, keyUp is not detected. I fixed it by switching from `.key` to `.code`. I also moved the methods inside the constructor for consistency.

Opened a PR on your fork since it changed a lot of lines

**Review by dylanebert — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
